Create printer-anycubic-kobra-max 2022.cfg
tomsbasement/CheaPad pull request #2
Opened 2023-06-29 15:58 UTC by Michel-lev

2023-06-30 04:58 UTC, bistory commented
Same remark as the other, can you also change the temperature sensor ? It refers to "Raspberry Pi" but the correct one is "rpi", you can check the other configurations :-)

2023-06-30 07:12 UTC, Michel-lev commented
bonjour modification faite

2023-06-30 09:42 UTC, bistory requested changes

2023-06-30 09:42 UTC, bistory commented on Anycubic/printer-anycubic-kobra-max-2022.cfg
> +[temperature_sensor RPi]
En fait c'est "host" la variable à utiliser, exemple : 
```
[temperature_sensor host]
sensor_type: temperature_host
```

2023-06-30 11:02 UTC, Michel-lev commented
fait

2024-02-21 09:49 UTC, bistory commented
Voila c'est ajouté ! Merci ;-)

2024-02-21 09:49 UTC, closed without merging